setup.template.enabled: false
setup.ilm.enabled: false

output.logstash:
  hosts: ["logstash-proxy:5044"]
  loadbalance: true
  worker: 2
  bulk_max_size: 2048
  timeout: 30
  max_retries: 3
  backoff:
    init: 1s
    max: 60s

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/mylogs/*.log

monitoring:
  enabled: true
  cloud.id: '${CLOUD_ID}'
  cloud.auth: '${CLOUD_AUTH}'
  cluster_uuid: "${CLUSTER_UUID}"